name: "Check for changes in paths"

on:
  workflow_call:
    outputs:
      actions:
        value: ${{ jobs.changed.outputs.actions }}
      website:
        value: ${{ jobs.changed.outputs.website }}

permissions:
  contents: read
  pull-requests: read

jobs:
  changed:
    runs-on: ubuntu-24.04
    outputs:
      actions: ${{ steps.changes.outputs.actions }}
      website: ${{ steps.changes.outputs.website }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: Paths Changes Filter
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: changes
        with:
          filters: |
            actions:
              - '.github/workflows/*.yml'
            website:
              - 'public/**/*'
              - 'src/**/*'
              - '.tool-versions'
              - 'astro.config.mjs'
              - 'package.json'
              - 'tsconfig.json'
